### DISCUSSION TITLE
Action entity refactor

### DISCUSSION THREAD

**Discussion by DrSmugleaf** [space-wizards/space-station-14#19944] [Code announcements]
The action refactor has been merged (<https://github.com/space-wizards/space-station-14/pull/19900>)

- Action prototypes must be replaced with entity prototypes.
  - This is done by changing `type: ...` with `type: entity`, and moving all data other than the `name`, `description` and new `id` field to an action component such as InstantAction. See below for an example.
  - This means that action names and descriptions are automatically localized.
- Any data fields that previously took in an action mapping data node must now take the id of the action entity prototype instead.
  - This also affects maps, which must be updated to be used if any actions were saved to them.
  - Most of the cases for this are with "toggleAction:" nodes which can be directly removed.
- For any downstream custom mapping actions, see the action migrator code example in <https://github.com/space-wizards/space-station-14/commit/ba026a4e4e4b3d0779d6cf20eee6d2c7a9c92277> to automatically map them to the new format.

Here's an example of an old action:
```yaml
- type: instantAction
  id: MechCycleEquipment
  name: action-name-mech-cycle
  description: action-description-mech-cycle
  itemIconStyle: NoItem
  icon: 
    sprite: Interface/Actions/actions_mecha.rsi
    state: mech_cycle_equip_on
  event: !type:MechToggleEquipmentEvent
  useDelay: 0.5
```

And its new version:
```yaml
- type: entity
  id: ActionMechCycleEquipment
  name: action-name-mech-cycle
  description: action-description-mech-cycle
  noSpawn: true
  components:
  - type: InstantAction
    itemIconStyle: NoItem
    icon:
      sprite: Interface/Actions/actions_mecha.rsi
      state: mech_cycle_equip_on
    event: !type:MechToggleEquipmentEvent
    useDelay: 0.5
```
