### ISSUE TITLE
You should be able to pet medibots

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#10093]
## Description
Medibots are cute. Here's a guide on how to pet them.

First you're going to want to open the `silicon.yml` in `/Resources/Prototypes/Entities/Mobs/NPCs/`, then search for `MobMedibot`

Create an InteractionPopup component with something like this. Copy and paste it under `components:`, remember that indention is key otherwise it wont work.

This is how you define components.

```
  - type: InteractionPopup # Name of component
    interactSuccessString: petting-success-medibot # Variables under component
    interactFailureString: petting-failure-generic
    interactSuccessSound:
      path: /Audio/PATH/TO/AUDIO/FILE # You'll have to create an audio file or just use an existing one.
```

Then go into `Resources/Locale/en-US/interaction/interaction-popup-component.ftl`, and add a new value. It should look something like this.

```
petting-success-medibot = You pet {THE($target)} on {POSS-ADJ($target)} cold metal head.
```

Feel free to be creative on the above! I wanna see how creative you are with this.

After that, you're done and ready to PR it

**Additional context**
Very beginner friendly PR with a step by step guide for anyone wanting to get into YAML. Don't be afraid to ask in #howdoicode
