### ISSUE TITLE
Construction node actions are called three times when switching entities

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#11028]
## Description

Actions defined on a node that also changes entity, it causes the actions to be run three times. Once [on the old entity](https://github.com/space-wizards/space-station-14/blob/c55a015b77da8169434175aa29b306c892153511/Content.Server/Construction/ConstructionSystem.Graph.cs#L236), once when [spawning the new entity](https://github.com/space-wizards/space-station-14/blob/c55a015b77da8169434175aa29b306c892153511/Content.Server/Construction/ConstructionSystem.Graph.cs#L280), and then once [after transferring containers](https://github.com/space-wizards/space-station-14/blob/c55a015b77da8169434175aa29b306c892153511/Content.Server/Construction/ConstructionSystem.Graph.cs#L332).

**Reproduction**

1. Make a constructionGraph node that defines `entity:` and `actions:`
2. Build to the node.
3. Code runs the defined `actions:` three times.

```yml
- type: entity
  name: dummy
  id: Dummy
  components:
  - type: Construction
    graph: DummyConstruction
    node: firstNode
  - type: Sprite
    sprite: error.rsi
    state: error
  - type: Clickable

- type: entity
  parent: Dummy
  name: dummy2
  id: Dummy2
  components:
  - type: Construction
    graph: DummyConstruction
    node: secondNode

- type: entity
  parent: BaseItem
  name: dummy counter
  id: DummyCounter
  components:
  - type: Sprite
    sprite: error.rsi
    state: error

- type: constructionGraph
  id: DummyConstruction
  start: start
  graph:
  - node: start
    edges:
    - to: firstNode
      steps:
      - material: Steel
        amount: 1

  - node: firstNode
    entity: Dummy
    edges:
    - to: secondNode
      steps:
      - tool: Screwing
    - to: start
      steps:
      - tool: Anchoring

  - node: secondNode
    entity: Dummy2
    actions:
    - !type:SpawnPrototype
      prototype: DummyCounter
    edges:
    - to: firstNode
      steps:
      - tool: Anchoring

- type: construction
  name: dummy construction
  id: DummyConstruction
  graph: DummyConstruction
  startNode: start
  targetNode: firstNode
  category: test
  objectType: Structure
  placementMode: SnapgridCenter
  icon:
    sprite: error.rsi
    state: error
```

**Additional context**

So far this hasn't really affected any construction, since actions on nodes are both rare and usually don't depend on previous state.
