### ISSUE TITLE
radioChannel prototypes don't work when uploaded

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#13662]
## Description
Using `loadprototype` to load a `radioChannel` doesn't seem to work. I get "no such channel" when uploading the following and trying to use the headset:
```
- type: radioChannel
  id: CE_Unregistered
  name: Unregistered
  keycode: 'r'
  frequency: 1453
  color: "#8f4a4b"

- type: entity
  parent: ClothingHeadset
  id: CE_ClothingHeadsetUnregistered
  name: unregistered headset
  description: A headset that has been modified to not require any local infrastructure and which does not use a registered channel.
  components:
    - type: Headset
      channels:
        - CE_Unregistered
    - type: Sprite
      sprite: Clothing/Ears/Headsets/mining.rsi
    - type: Clothing
      sprite: Clothing/Ears/Headsets/mining.rsiaw
```
