### ISSUE TITLE
Atmos rounding errors

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#14287]
## Description

Likely due to rounding issues in gas reactions, setups like the one below seem to be able to generate orders of magnitude more of frezon than the input mols of tritium.

**Reproduction**

In the example, the culprit appears to be the mixer settings, everything else that looks weird when compared to normal uses of the atmos devices appears to be done for efficiency reasons.

**Screenshots**

![image](https://user-images.githubusercontent.com/119664036/221404849-e848be81-3325-4a13-8476-b0eaaef1a1a0.png)
Settings for mixer at the bottom. Tritium is on the primary port.
![image](https://user-images.githubusercontent.com/119664036/221404870-a6a426b4-9ada-44c8-96a6-3d99e782aee2.png)

**Comment by Ilya246** [comment]
that's my frezon setup and no, that's not what it does, the frezon reaction actually only needs trit as a catalyst - trit and oxygen are completely interchangeable in it and it consumes both proportionally to how much there are, which means you only need trit to be present for frezon to mix

**Comment by Cheackraze** [comment]
That's 

> that's my frezon setup and no, that's not what it does, the frezon reaction actually only needs trit as a catalyst - trit and oxygen are completely interchangeable in it and it consumes both proportionally to how much there are, which means you only need trit to be present for frezon to mix

This is not the intended design

**Comment by deltanedas** [comment]
then change it to burn trit rather than use it as a catalyst

**Comment by Partmedia** [comment]
> This is not the intended design

Unfortunately, this is what the code does. What did you understand as the *intention* for this reaction? That's probably what we should change it to.

Right now, this reaction goes something like:

1. Is there a minimum 0.01 moles of tritium required to start this reaction? If so, continue.
2. Sum the *total* moles of oxygen and tritium, produce that much freezon, remove the reactants.

I think the part that is unintuitive is exactly that "trit and oxygen are completely interchangeable", flies in the face of most chemical reactions we know here on Earth. I think(?) we intended to require equal parts oxygen and tritium? Perhaps @mirrorcult , the original author, could chime in on design intent.

**Comment by Partmedia** [comment]
Sources:

Minimum needed to start reaction:
```
- type: gasReaction
  id: FrezonProduction
  priority: 2
  maximumTemperature: 73.15 # Cold tritium fire, basically.
  minimumRequirements:
  - 0.01  # oxygen
  - 0.01  # nitrogen
  - 0     # carbon dioxide
  - 0     # plasma
  - 0.01  # tritium
  - 0     # vapor
  - 0     # miasma
  - 0     # n2o
  - 0     # frezon
  effects:
  - !type:FrezonProductionReaction {}
```

Actual reaction:
```
        var initialN2 = mixture.GetMoles(Gas.Nitrogen);
        var initialOxy = mixture.GetMoles(Gas.Oxygen);
        var initialTrit = mixture.GetMoles(Gas.Tritium);

        var oxyConversion = initialOxy / Atmospherics.FrezonProductionConversionRate;
        var tritConversion = initialTrit / Atmospherics.FrezonProductionConversionRate;
        var total = oxyConversion + tritConversion;

        // some efficiency calculation removed for clairty

        mixture.AdjustMoles(Gas.Oxygen, -oxyConversion);
        mixture.AdjustMoles(Gas.Tritium, -tritConversion);
        mixture.AdjustMoles(Gas.Frezon, total * efficiency);
```
