### ISSUE TITLE
Chemistry

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14#170]
Entities need to be able to contain reagents, and this system controls it.

**Comment by PrPleGoo** [comment]
Make some Reagent prototype.
This reagent prototype should implement some IMetabolizable interface.
Metabolizer can be a Component on mobs or whatever with an enum type.
The Metabolizer loops through a List<IMetabolizable> that it gets from the solution.

The implementation of such an IMetabolizable would look something like this initially:
```
public class Beer : IMetabolizable
{
	private int Strength;
	public void Metabolize(Metabolizer metabolizer, float frameTime){
		metabolizer.dizzness+=Strength * frameTime;
	}
}
```
But if you want the metabolizers type to infuence that, say a metabolism reacts differently to a reagent.
You need to either:
```
public void Metabolize(Metabolizer metabolizer, float frameTime){
	switch(metabolizer.Type)
	{
		case(Cat):
			MyPrivateMethod();
			break;
		case(Human):
		default:
			metabolizer.dizzness+= Strength * frameTime
			break;
	}
}
```
But that would be disgusting.
Instead add a dictionary that can be filled via YML on the Reagent prototype.
Then the implementation could look like this:
```
public void Metabolize(Metabolizer metabolizer, float frameTime){
{
	_dictionary.TryGetValue(metabolizer.Type)?.Metabolize(metabolizer, frameTime);//not sure if TryGetValue is a thing on dictionaries, if not check for the key or whatever
}
```
The resulting YML could look a little like this:
```
- type:reagent
  name: beer
  - type: handler
    metabolism: cat
    behavior:
    - type: DoThing
  - type: handler
    metabolism: human
    behavior:
    - type: MakeDizzy
```
With a MakeDizzy implementation as such:
```
public class MakeDizzy : IMetabolizable
{
	public void Metabolize(Metabolizer metabolizer, float frameTime){
	{
		metabolizer.dizzness+=10 * frameTime
	}
}
```
Because the specific behaviors are defined genericly they can also be initialized with different values:
```
- type:reagent
  name: beer
  - type: handler
    metabolism: human
    behavior:
    - type: MakeDizzy
      strength: 5
    - type: AddFood
      nutrition: 5
```
```
- type:reagent
  name: fancy beer
  - type: handler
    metabolism: human
    behavior:
    - type: MakeDizzy
      strength: 8
    - type: AddFood
      nutrition: 8
```
```
- type:reagent
  name: vodka
  - type: handler
    metabolism: human
    behavior:
    - type: MakeDizzy
      strength: 40
```
In the YML you could even define a some extra behaviors bound as a field.
Maybe a default behavior that happens only when the reagent doesn't have a handler for your MetabolismType.
And a default behavior that just always happens.
Beer's YML could look a little like this:
```
- type:reagent
  name: beer
  - type: handler
    defaultExcludedBehavior:
    - type: MakeDizzy
    - type: AddFood
  - type: handler
    metabolism: rockPeople
    behavior:
    - type: AddFood
```
Pretty sure I'm messing up how to write YML here so take it all with a grain of salt.
