### ISSUE TITLE
Device network issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#17136]
See https://github.com/DeltaV-Station/Delta-v/pull/57

Invalid entity ids still get serialized and looks like shutdownsubscribers just dupes devices anyway.

Ideally devices would just get tracked with no need for 2 separate implementations I think.

![image](https://github.com/space-wizards/space-station-14/assets/31366439/88bbd0fc-9d16-4dea-bd27-11defc591dfc)

**Comment by juliangiebel** [comment]
Those are not 2 separate implementations for the same thing. `ShutdownSubscribers` is a property inside `DeviceNetworkComponent` which is used to notify other systems when a device is removed. Like the device list or device link systems.

It looks duped because one is the `ShutdownSubscribers` list inside the  `DeviceNetworkComponent` and the other is the list of devices saved inside the `DeviceListComponent`.
The list of shutdown subscribers in the screenshot isn't actually the "important" part. Important is the shutdown subscriber list on the devices that are saved inside the `DeviceListComponents` device list.
Like this one:
```yml
  - uid: 2740
    components:
    - rot: 1.5707963267948966 rad
      pos: -7.5,43.5
      parent: 2
      type: Transform
    - ShutdownSubscribers:
      - 5 #This is the air alarms entitiUid
      type: DeviceNetwork
    - enabled: False
      type: AmbientSound
    - nextSound: 4074.8548356
      type: EmitSoundOnCollide
```
The shudown subscriber list is "bidirectional".

The actual bug is that a device got removed without being removed from the shutdown subscriber list.
