### ISSUE TITLE
Transform datafields should be inline on map files

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#18323]
It lets you save an extra line per transformcomponent for stonks.

So

```
- proto: Window
  entities:
  - uid: 37
    components:
    - pos: 0.5,-2.5
      parent: 181
      type: Transform
  - uid: 46
    components:
    - pos: -5.5,-1.5
      parent: 181
      type: Transform
```

becomes

```
- proto: Window
  entities:
  - uid: 37
    pos: 0.5,-2.5
    parent: 181
  - uid: 46
    pos: -5.5,-1.5
    parent: 181
```

(where no comps found which is 90% of entities you also save the extra line).
