### ISSUE TITLE
Some animal dead states throw a exception

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#1941]
The tarantula:
```
    visuals:
    - type: DamageStateVisualizer
      normal: tarantula
      dead: dead
```

The texture folder:
![grafik](https://user-images.githubusercontent.com/17885980/91464057-6c675c00-e88c-11ea-9a30-3a5c28935821.png)

dead => tarantula_dead

There may be other ones

Also we have different sprites, but they aren't spawned as different types ingame. 
Do we need like a randomizer component for that or is that just not used in the yaml?
