### ISSUE TITLE
Clickable objects works bad with sprites that could have different rendering strategy on it's layers

### ISSUE THREAD

**Issue by CaptainSqrBeard** [space-wizards/space-station-14#19619]
## Description
While doing my PR #19607 I got an issue while making sprite state of rolled poster follow `Default` render strategy insteand of `SnapToCardinals`. Visually it looks good, but clickable area actually doesn't follow sprite and probably still being snapped to cardinals.

**Reproduction**
1. Create an object that has different render strategies on it's sprite layers. You can see my object in details below
2. Rotate it any way
3. Try hover your cursor on it

<details>

```yaml
- type: entity
  parent: PosterBase
  id: PosterContrabandFreeTontoUnstuck
  suffix: Unstuck
  name: "Free Tonto"
  description: "A salvaged shred of a much larger flag, colors bled together and faded from age."
  components:
  - type: Sprite
    sprite: Structures/Wallmounts/posters.rsi
    layers:
    - state: rolled_contraband
      renderingStrategy: Default
      map: ["unstuck"]
    - state: poster1_contraband
      map: ["stuck"]
      visible: false

# parent
- type: entity
  parent: BaseSignStickable
  id: PosterBase
  abstract: true
  components:
  - type: Sticky
    stickDelay: 3
    unstickDelay: 3
  - type: Sprite
    sprite: Structures/Wallmounts/posters.rsi
    granularLayersRendering: true
    snapCardinals: true
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.StickyVisuals.IsStuck:
        stuck:
          True: { visible: true }
          False: { visible: false }
        unstuck:
          True: { visible: false }
          False: { visible: true }
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 5
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/Effects/poster_broken.ogg
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        transferStickSurface: true
        spawn:
          PosterBrokenUnstuck:
            min: 1
            max: 1
        offset: 0
```
</details>

**Screenshots**
Look on cursor

https://github.com/space-wizards/space-station-14/assets/56765288/88cd76b1-9d82-4f3c-9e9c-27a185037fb7

**Additional context**
