### ISSUE TITLE
Head lockers have copy-paste spam everywhere

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#24762]
Gonna murder whoever saw this and thought "yeah this is fine".

```
- type: entity
  id: LockerChiefEngineerFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerChiefEngineer
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterHardsuitEngineeringWhite
      - id: ClothingMaskBreath
      - id: OxygenTankFilled
      - id: NitrogenTankFilled
      - id: ClothingEyesGlassesMeson
      - id: ClothingBeltChiefEngineerFilled
      - id: ClothingShoesBootsMagAdv
      - id: ClothingHandsGlovesColorYellow
      - id: CigarCase
        prob: 0.15
      - id: DoorRemoteEngineering
      - id: RubberStampCE
      - id: JetpackVoidFilled
      - id: ClothingHeadsetAltEngineering
      - id: BoxEncryptionKeyEngineering
      - id: AccessConfigurator
      - id: RCD
      - id: RCDAmmo

- type: entity
  id: LockerChiefEngineerFilled
  suffix: Filled
  parent: LockerChiefEngineer
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesMeson
      - id: ClothingBeltChiefEngineerFilled
      - id: ClothingHandsGlovesColorYellow
      - id: CigarCase
        prob: 0.15
      - id: DoorRemoteEngineering
      - id: RubberStampCE
      - id: ClothingHeadsetAltEngineering
      - id: BoxEncryptionKeyEngineering
      - id: AccessConfigurator
      - id: RCD
      - id: RCDAmmo
```
