### ISSUE TITLE
Oasis has the chance to get a roundstart assholesledgehammer

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#27688]
## Description

It deals 50 blunt damage a hit. That's not really okay.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Plykiya** [comment]
wait, does this item not even fucking exist? 
![image](https://github.com/space-wizards/space-station-14/assets/58439124/2c4fb774-d95c-4095-85fc-303b1f2386a2)

what the fuck happened on lizard round 52857 then....

**Comment by Plykiya** [comment]
![image](https://github.com/space-wizards/space-station-14/assets/58439124/1119b58a-dac1-4f77-861f-35ab25194fec)

well, here's an image as proof at least

**Comment by mirrorcult** [comment]
is this not just an admin uploaded item

**Comment by asperger-sind** [comment]
> is this not just an admin uploaded item

Looks like a VV'ed version of the hammer from #21243?
Looking at resources/maps/oasis.yml you can find this:
```yml
- proto: Sledgehammer
  entities:
  - uid: 10291
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: -12.085021,-50.48558
      parent: 2
```
