### ISSUE TITLE
air alarm pressure settings are stupidly high

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#28192]
## Description
they will be warning at like 90kpa and close firelocks at 80kpa, both of which are completely safe to everyone.
this means nobody cares about firelocks because half the time theyre down for no good reason

**Comment by PJB3005** [comment]
Read the comment nerd

```yml
  lowerBound: !type:AlarmThresholdSetting
    # Actual low pressure damage threshold is at 20 kPa, but below ~85 kPa you can't breathe due to lack of oxygen.
    threshold: 85
```
https://github.com/space-wizards/space-station-14/blob/dbb7dcd16d97d7cf7a7d1430a07bb24cce55c3d9/Resources/Prototypes/Atmospherics/thresholds.yml#L16C1-L18C18
You can't lower them.
