### ISSUE TITLE
In-hand guns that are reloaded with an ammo provider do not update their ammo counter until you shoot

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#28550]
Tested with the pump shotgun and box of buckshot shells in cm
```yml
﻿- type: entity
  parent: BaseWeaponShotgun
  name: M37A2 Pump Shotgun
  id: WeaponShotgunM37A2
  description: An Armat Battlefield Systems classic design, the M37A2 combines close-range firepower with long term reliability. Needs to be pumped.
  components:
  - type: Sprite
    sprite: _CM14/Objects/Weapons/Guns/Shotguns/m37a2.rsi
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
  - type: Clothing
    sprite: _CM14/Objects/Weapons/Guns/Shotguns/m37a2.rsi
    quickEquip: false
    slots:
    - Back
    - SuitStorage
  - type: Wieldable
  - type: Gun
    soundGunshot:
      path: /Audio/_CM14/Weapons/Guns/Gunshots/gun_shotgun.ogg
  - type: BallisticAmmoProvider
    cycleable: false
    whitelist:
      tags:
      - CMShellShotgun
    capacity: 9
    proto: null
    soundInsert:
      path: /Audio/_CM14/Weapons/Guns/Reload/m37a2.ogg
  - type: PumpAction
  - type: ShootUseDelay
    delay: 2
  - type: UseDelay
```

```yml
﻿- type: entity
  abstract: true
  name: box of shotgun shells
  parent: AmmoProviderShotgunShell
  id: CMBoxShotgunBase
  components:
  - type: BallisticAmmoProvider
    proto: CMShellShotgunBase
  - type: Sprite
    sprite: _CM14/Objects/Weapons/Guns/Ammunition/Boxes/shotgun_boxes.rsi
  - type: CMAmmoBox
```
