### ISSUE TITLE
Onboarding/Tutorial System

### ISSUE THREAD

**Issue by Jezithyr** [space-wizards/space-station-14#28616]
We need to implement a tutorial/onboarding experience for new players that explains the basic game controls and interface. Ideally this should be expandable/customizable by downstream/forks through yaml or config. To implement this as fast as possible (hopefully before the influx of players from PCTide), we should focus on getting this implemented as fast as possible and worry about supporting expansion/customization at a later date. 

Part 1 is a system for allowing players to select tutorial/onboarding depth, from none to "everything" and can be used for both onboarding and other possible tutorial systems.

The first thing we need for onboarding/tutorialization is having some way of toggling/querying a user's onboarding preferences:
- [ ] *New players* are shown a selection menu when spawning in on a server/fork that shows 4 options (in the future there will be an optional 5th): No Onboarding, Familiar with SS13, Familiar with Top-down RPGs, Full Tutorial.
- [ ] Selecting an option will save the selected onboarding level to the either the server database or the player's local datafile.
- [ ] An additional "on-boarding progress" value will be stored in the same way, and can be incremented and saved to keep track of which part of onboarding that a player is in.
- [ ] A "completed onboarding" boolean that is saved in the same way, this boolean is set when the user selects "No onboarding", completes the onboarding or presses the dismiss/end button in onboarding.

Part 2 is the specifics for the onboarding system

For the actual onboarding system:
- [ ] Onboarding would be triggered after a player selected an onboarding option OR spawns in after rejoining/reconnecting (which resumes the last onboarding step)

Onboarding would have multiple helper methods that allow for UI prompts/highlights to be displayed and dismissed. Specifically:
- [ ] Highlighting a UI element with an arrow or other visual highlight. 
- [ ] Highlight an ingame entity with an arrow/pointer or other visual indicator
- [ ] Attach a text box at an offset to a UI element. With support for "pages" that a player can click through
- [ ] Highlight a Keybind that a player needs to press
- [ ] Highlights can be dismissed by mousing over/clicking on the UI element or after clicking through a linked textbox.
- [ ] A togglable textbox on the HUD with pages and a dismiss button for displaying onboarding tips

Onboarding hints would be triggered via hooking/subscribing to events that are raised in code
- [ ] Create a system that allows raising/subscribing to onboardingEvents
- [ ] Onboarding highlights/hints listening would be enabled/disable depending on the onboarding progress variable
- [ ] Players can click a "Dismiss tutorial" button at the top of the screen at any time during onboarding to end/exit out of onboarding.

An "Onboarding flow" is a defined onboarding "flow"/sequence that defines the number of and specific onboarding steps present in an instance of onboarding. Each option selected in part 1 (except for no onboarding) will correspond to an "Onboarding flow".
- [ ] Onboarding Step Prototype allows for linking together event listeners, UI highlight tags and description sequences.
- [ ] Onboarding flow has a list of OnboardingSteps which specify the order and flow of the onboarding.

**Comment by clement-or** [comment]
I've been wanting to tackle this in a PR for some time and I might give it a shot if that's alright.
My idea would be contextual popups on the side of the screen like some RPGs I used to play had. You get prompts to do something, when the action succeeds it goes onto the next step.

So for example, when you connect, it says "move using WASD", when that is done, the next step is triggered (for example : left click an object to take it etc). Any step can be skipped by the player. There would be a few "obligatory" steps that trigger the first time player connects, but otherwise such tutorials would be contextual.

Each tutorial has a trigger that can be a timer, a random trigger for game tips, or if you interact with a system for the first time, that tutorial is shown instead. It can also be on your first job join.

Our best bet is to have it open by default and make it opt-out. When you close the popup, it asks you if you want to disable the tutorials altogether, and explains that you can opt-in or out in the settings. The completed tutorial steps should be stored client-side (or on the account), either for each server separately, or the forks could specify when defining a tutorial step if it overrides the default one, so that only the non-default ones are shown when you join a new fork.

Ideally, there would also be a menu regrouping all tutorials so you can check them later.

**Comment by clement-or** [comment]
This is a sample OnboardingFlow prototype I came up with. Please let me know if that's a good way to implement this
```yml
- type: onboardingFlow
  id: LearnMovementsFlow
  trigger: !type:PlayerSpawnEvent   # Here valid EntityEventArgs
  priority: 0                       # The higher priority flows will be played over low priority ones when multiple valid flows can be played
  interrupt: false        # Onboarding flows can interrupt ongoing ones (eg. When emergency shuttle is called for the first time, the newcomer should be explained what it is and informed to go there asap)
  steps:
    - content:
      - type: !type:SimpleText
        text: "Press WASD to move"
      resolve: !type:PlayerMoveEvent  # Valid EntityEventArgs
    - content:
      - type: !type:HighlightClosest
        entityType: Sunglasses
        text: "Click on an object to pick it up"
      resolve:
        type: !type:PlayerPickupEvent
        entityType: Sunglasses
    - content:
      - type: !type:MultiPageContent
        pages:
          - type: !type:SimpleText
            text: "Did you know you can throw items?"
          - type: !type:SimpleText
            text: "It's very cool"
      resolve: !type:PlayerPickupEvent

```
