### ISSUE TITLE
Default keybind for "Toggle round end summary window"

### ISSUE THREAD

**Issue by joelsgp** [space-wizards/space-station-14#30427]
## Description
Currently the key to open the end of round summary window is unbound by default. It's a useful key and in our server we're always having to tell people to go and add a binding in settings to use it.

I think "End" is a decent key for it, this just needs to be added to keybinds.yml:
```yml
- function: ToggleRoundEndSummaryWindow
  type: Toggle
  key: End
```

I can open a pr if it's an ok idea
