### ISSUE TITLE
issue with prototypes

### ISSUE THREAD

**Issue by tvoiotchim12** [space-wizards/space-station-14#30578]
## Description

**Reproduction**

**Screenshots**

![Снимок экрана (232)](https://github.com/user-attachments/assets/ae2a4ca6-5953-40ef-89c9-c87dac7477ad)

**Additional context**

**Comment by IProduceWidgets** [comment]
Can you post the prototype?

**Comment by tvoiotchim12** [comment]
```
- type: entity
  parent: SimpleMobBase
  id: LPPMAW1
  name: гигаМАВ
  description: Всего лишь маленький котенок.
  components:
  - type: Sprite
    drawdepth: Mobs
    sprite: /Uploaded/maws.rsi
    layers:
    - map: ["enum.DamageStateVisualLayers.Base"]
      state: mawgiga
  - type: MobState
    allowedStates:
    - Alive
    - Dead
  - type: MobThresholds
    thresholds:
      0: Alive
      350: Dead
  - type: MovementSpeedModifier
    baseWalkSpeed: 4.5
    baseSprintSpeed: 4.5
  - type: MeleeWeapon
    soundHit:
        path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
    angle: 0
    animation: WeaponArcClaw
    damage:
      types:
        Blunt: 20
  - type: Hands
  - type: Speech
    speechSounds: Cat
  - type: InteractionPopup
    successChance: 0.7
    interactSuccessString: petting-success-cat
    interactFailureString: petting-failure-generic
    interactSuccessSpawn: EffectHearts
    interactSuccessSound:
      path: /Audio/Animals/cat_meow.ogg
      ```
      This is a problem with all prototypes
