### ISSUE TITLE
need map entity prototypes

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#30999]
## Description
instead of the map entity being proto: "" and copy paste the same special components onto every map yml or you break the map subtly or not subtly, there should be a `BaseMap` entity prototype with Gravity Broadphrase etc then have something like

```yml
- proto: BaseMap
  entities:
  - uid: 1
    components:
    - type: MetaData
      name: Saltern
```

make maps a tiny bit smaller and a lot more bug resistant, and lets you update the map entity without having to edit every map file
