### ISSUE TITLE
Need a spell / "action" system

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#31023]
Current issue is you get every single system re-inventing the wheel trying to do "hey cast a fireball, hey spawn an entity on cursor / around cursor". Magic does this, mime power does this, goliath does this, probably more I'm unaware of.

Ideally this would all be done via the same system and be compositional.
e.g.

```
- type: spell
  id: Weh
  actions:
  - !type:SpawnEntityOnCursor
    limit: 1
  targets:
  - !type:TilesPerpendicular
    width: 3

- type: spell
  id: Weh2
  actions:
  - !type:SpawnEntityOnCursor
  targets:
  - !type:TilesInCircle
    radius: 5
```
