### ISSUE TITLE
Crew Monitoring Server missing comps when mapped

### ISSUE THREAD

**Issue by IamVelcroboy** [space-wizards/space-station-14#31657]
## Description
Not sure exactly when it happened but maps with an existing `crewmonitoringserver` have this comp 
```yml
 - type: SingletonDeviceNetServer
   active: False
   available: False
```
New maps adding the CM Server, or when replacing the server in existing maps, that particular node is missing/not being added. 

Effectively making the Crew Monitor not work when the map is initialized.  

**Reproduction**
- Map CM Server
- Start map
- Look at Crew Monitor
- No worky

**Screenshots**
n/a

**Additional context**
This has been happening since early June but I'm not sure exactly where it broke.
