### ISSUE TITLE
leaving out "type:" from an entity table definition can cause server to stack overflow on startup

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#31695]
## Description
obviously its an error but it should do something better than stack overflow and leave me guessing as to why its being trolled

```yaml
- type: entityTable
  id: GamingTable
  table: !AllSelector # missing type:, enjoy your stack overflow
    children:
    - id: EnergySword
```
