### ISSUE TITLE
Headphones will no longer give the alternative activated sprite

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#31755]
## Description
Regardless of activated or deactivated, headphones no longer have the little notes.

**Reproduction**
Turn on headphones
Wear them
Cry

**Screenshots**
![20240902094830_1](https://github.com/user-attachments/assets/fe013a6b-1c5b-4919-b89f-eef9d305821b)

**Additional context**
This physically hurts me.

**Comment by Boaz1111** [comment]
@slarticodefast you wanted more instances of broken itemtoggle, aye?

**Comment by Everturning** [comment]
Also wanted to mention that for some reason I can't put them on, but that may be worth its own issue

**Comment by Azzizi** [comment]
Looking into this now to dip my toes into contribution; headphones are set up with 
```
type: ToggleableLightVisuals
    spriteLayer: enum.ToggleVisuals.Layer
    clothingVisuals:
      neck:
      - state: on-equipped-NECK
```
in Clothing/Neck/misc.yml

Looking at other items with this type, this appears to be incorrect syntax and should be a simple correction-- I'm working on hammering it out now.
