### ISSUE TITLE
constructionGraph prototype step needs improvement.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3326]
## Description

Construction prototype steps should allow specifying of amounts, or else you get this.

Otherwise this.
```yaml
        - to: ground
          steps:
            - prototype: LeavesTobaccoDried
              icon:
                sprite: Objects/Specific/Hydroponics/tobacco.rsi
                state: dried
              name: dried tobacco leaves
            - prototype: LeavesTobaccoDried
              icon:
                sprite: Objects/Specific/Hydroponics/tobacco.rsi
                state: dried
              name: dried tobacco leaves
              doAfter: 5
```

With this graph, you also get this kind of funky description in-game.
![image](https://user-images.githubusercontent.com/49448379/108570404-b72ad380-7305-11eb-8b1f-88cbd8c42948.png)

Instead of that, it should look like:

```
To craft this item you need:
    2 dried tobacco leaves
```

For prototypes, I don't think you need the numbered steps.

This might be an issue with IconComponent as a whole, but you should also be able to define the color of the icon in the recipe materials and the recipe icon, like this.
```yaml
icon:
  sprite: Objects/Misc/reageant_fillings.rsi
  state: powderpile
  color: brown
```
