### ISSUE TITLE
Inserting into Storage is broken when the StorageComponent is defined after the ContainerContainer

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#33681]
## Description
Something really weird is going on depending on the order the components are defined.
Here are two identical test prototypes to repoduce the bug.

**Reproduction**
```
- type: entity
  name: TestWorking
  suffix: test
  id: BackpackTest1
  description: This one works
  components:
  - type: Sprite
    sprite: Clothing/Back/Backpacks/backpack.rsi
    state: icon
  - type: Item
    size: Huge
  - type: Storage # above ContainerContainer
    grid:
    - 0,0,1,2
    maxItemSize: Huge
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: UseDelay
    delay: 0.5
  - type: Physics
    bodyType: Dynamic
  - type: Clickable
  - type: InteractionOutline

- type: entity
  name: TestBroken
  suffix: test
  id: BackpackTest2
  description: This one is broken
  components:
  - type: Sprite
    sprite: Clothing/Back/Backpacks/backpack.rsi
    state: icon
  - type: Item
    size: Huge
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: Storage # below ContainerContainer
    grid:
    - 0,0,1,2
    maxItemSize: Huge
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: UseDelay
    delay: 0.5
  - type: Physics
    bodyType: Dynamic
  - type: Clickable
  - type: InteractionOutline
```
- spawn both of these test entities
- open them and put a small item into the grid storage
- the broken one will mispredict, then always place the item in the first available slot, no matter where you clicked
- the other one will work fine
