### ISSUE TITLE
doesn`t clearing existing

### ISSUE THREAD

**Issue by Ratyyy** [space-wizards/space-station-14#33877]
## Description

RoomFillComponent.ClearExisting doesn`t work on mapinited maps
**Reproduction**

1. use this prototype:
```
- type: entity
  id: VGRoidInteriorRoomMarker
  parent: BaseRoomMarker
  name: VGRoid interior marker
  components:
  - type: RoomFill
    clearExisting: true
    roomWhitelist:
      tags:
      - VGRoidInterior
```
2. spawn VGRoid interior marker on mapinited map
3. to see that ClearExisting doesn't work.
**Screenshots**

https://github.com/user-attachments/assets/add4ed5f-4d38-4591-b2e8-efa6ab5247de

**Additional context**

sometimes it works, so repeat it a few times
