### ISSUE TITLE
Many food utensil restrictions seem abitrary.

### ISSUE THREAD

**Issue by Alpaccalypse** [space-wizards/space-station-14#34255]
## Description
Ignoring the fact that it seems like you can eat anything with your hands, there are many inconsistencies with utensil use for foods. This primarily relates to being able to eat some foods with a fork or chopsticks, but not with a knife or spoon. One or the other of these often makes sense, but often both do not.

**Reproduction**
Some examples eaten with chopsticks and fork but not a knife or spoon:

- Boiled egg
- Cakes
- Cake batter
- Cheese
- Doughs
- Fruit
- Packaged foods
- Pies
- Cocoa beans
- Various egg dishes
- Ice cream sundae
- Stick of butter
- Tofu

**Additional context**
Can't eat an ice cream sundae with a spoon, but can with chopsticks? Can't spike myself some cheese on a knife, but can eat it with a fork? Can eat cake batter with a fork, but not with a spoon?

**Related issues & pull requests**
#34172
#34179
#34254

**Comment by Alpaccalypse** [comment]
So apparently fork is the default utensil, and chopsticks are defined as forks, which explains most of this, though doesn't really negate the issue.

**Comment by Gavin-TC** [comment]
Hey, just wanted to point out that for rice, where you should be able to use multiple utensils, you can simply do something like:
```
# Rice
- type: entity
  parent: FoodBowlBase
  id: FoodRiceBase
  abstract: true
  components:
  - type: Food
    trash:
    - FoodBowlBig
# Change is here vvvvv
    utensil:
    - Spoon
    - Fork
    ...
```
Tested this in my own branch and it seemed to work fine. Feel like this would be a good addition/change to food. This base seems to be really the only one of the new bases you made that this fits with.
