### ISSUE TITLE
RadiationSource behaves stangely at low intensity

### ISSUE THREAD

**Issue by Alpaccalypse** [space-wizards/space-station-14#34456]
## Description
If you have the `RadiationSource` component on an entity set to `intensity: 0.1` they will never register on the geiger counter or cause any radiation poisoning. Changing `slope` to any value still results in no radiation. If you set intensity at 0.105, 0.11 etc, then it will behave as expected.

If you make a stack of 2 of this 0.1 intensity entity and place it in the environment or carry it, it will emit radiation, at approximately the correct values. Changing the slope value seems to cause minor variation from expected values when comparing the output of different stacks.

I have exhausted myself testing for now, but I think there is also a problem with something in the calculation mutliplying when it should be adding, or maybe some kind of compound error with the sum of the base values.

**Reproduction**

You can start testing it with something like this:
```
- type: entity
  parent: OreBase
  id: RadBase1
  suffix: rad ore test 11
  components:
  - type: Sprite
    state: uranium
  - type: Material
  - type: RadiationSource
    intensity: 0.11
    slope: 0.1
```

**Screenshots**
Intensity 0.11, slope 09, stack of two.
![image](https://github.com/user-attachments/assets/8b5793b0-105d-495e-a951-60f26958bdf2)
Intensity 0.1, slope 09, stack of two.
![image](https://github.com/user-attachments/assets/66ce7c64-dd58-42b3-beb9-9bea78bd370e)

This might be expected, but it always seems to be off, even accounting for .01 and multiplication of values.

**Additional context**
I am so tired of testing this, and I might have either missed something obvious or made an obvious mistake somewhere, but I am certain that at least something is wrong here with it not registering 0.1 intensity correctly.
