### ISSUE TITLE
False-positives with serv3

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3508]
## Description

This is an EXAMPLE of many. Part of why there's a bunch of sprite errors in the console right now.

So basically, hardhats have this set in their base entity.
```yaml
  - type: Sprite
    layers:
    - state: icon
    - state: light-icon
      shader: unshaded
      visible: false

```
This makes the game freak out since it thinks there isn't a sprite defined for this, when infact there is in it's children as seen here.

```yaml
- type: entity
  parent: ClothingHeadHatHardhatBase
  id: ClothingHeadHatHardhatBlue
  name: blue hard hat
  description: A hard hat, painted in blue, used in dangerous working conditions to protect the head. Comes with a built-in flashlight.
  components:
  - type: Sprite
    sprite: Clothing/Head/Hardhats/blue.rsi
  - type: Clothing
    sprite: Clothing/Head/Hardhats/blue.rsi
```

**Incomplete List**
headsets_alt.yml
