### ISSUE TITLE
Vegetable Pizza Slice can hold as much reagents as Full Vegetable Pizza

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#35261]
## Description

Slice of Vegetable Pizza have maximum volume of 40u, but have reagents for only 6u.
(*i think you can inject Veg Pizza Slice with shitton of lexorin/poison to kill someone in one bite, didnt test it thou*)

```
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 40
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: JuiceCarrot
          Quantity: 1
        - ReagentId: Vitamin
          Quantity: 1
```
from `Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/pizza.yml` on line `226`
