### ISSUE TITLE
AutoImplant component is not always inherited properly

### ISSUE THREAD

**Issue by M1tht1c** [space-wizards/space-station-14#36372]
## Description
When a parent entity has the AutoImplant component, any children entities with an autoimplant component will override it, instead of getting implants from both versions

**Reproduction**
Put this YAML in humanoids.yaml, and see how the child test has no light implant, but a horn implant (the two other spawners are just there for sanity checks to make sure the other cases are working)

``` yaml
- type: randomHumanoidSettings
  id: TestHumanoidParent
  parent: EventHumanoid
  components:
    - type: AutoImplant
      implants:
      - LightImplant

- type: entity
  id: TestHumanoidParentSpawner
  name: Test Parent Spawner
  suffix: test
  components:
    - type: RandomHumanoidSpawner
      settings: TestHumanoidParent

- type: randomHumanoidSettings
  id: TestHumanoidChild
  parent: TestHumanoidParent
  components:
  - type: AutoImplant
    implants:
    - BikeHornImplant

- type: entity
  id: TestHumanoidChildSpawner
  name: Test Child Spawner
  suffix: test
  components:
  - type: RandomHumanoidSpawner
    settings: TestHumanoidChild

- type: randomHumanoidSettings
  id: TestHumanoid
  parent: EventHumanoid
  components:
  - type: AutoImplant
    implants:
    - BikeHornImplant
    - LightImplant

- type: entity
  id: TestHumanoidSpawner
  name: Test Spawner
  suffix: test
  components:
  - type: RandomHumanoidSpawner
    settings: TestHumanoid
```

**Additional context**
This very well might not be a bug, and just a consequence of how the ECS works, but even so I've seen it cause issues a couple of times so I figured I would report it.

**Comment by M1tht1c** [comment]
Might also have something to do with https://github.com/space-wizards/space-station-14/issues/35833

**Comment by Tayrtahn** [comment]
This is a consequence of how prototype inheritance works (currently). The same issue comes up with tags pretty frequently.

Fields defined in the components of child prototypes overwrite those values from the parents. This makes intuitive sense when those fields are simple values:

```
- type: entity 
  id: EmergencyLight
  components:
  - type: testLight
    brightness: 5
    color: red

- type: entity
  parent: EmergencyLight
  id: EmergencyLightBlue
  components:
  - type: testLight
    color: blue
```
Makes sense, right? You want `color` in the child to replace the value in the parent.

The problem is when a field is a collection type, like a list or dictionary:

```
- type: entity 
  id: OneCardHolder
  components:
  - type: cardHolder
    cards:
    - Ace

- type: entity
  parent: OneCardHolder
  id: TwoCardHolder
  components:
  - type: cardHolder
    cards:
    - King
```
The same thing happens as before: the value of `cards` in the child overwrites the value from the parent, and `TwoCardHolder` has only one card: the king.

To make things more complicated, sometimes that behavior actually is desired for collections too - with tags, for example, it can be useful to remove a tag that isn't appropriate for the child entity to have.

It would be nice to have more options for these situations. Some sort of way of indicating that instead of _replacing_ the parent's value, any new values should be _added_ to the existing collection. This would require engine changes, and has been requested before, but it's fairly complicated.
