### ISSUE TITLE
Singulo shader fucks up mapping

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3670]
## Description

Reproduce
1. Go to `~/Resources/Maps/`
2. Open `saltern.yml`
3. Scroll to bottom
4. Paste
```yml
- uid: 4724
  type: SingularityToy
  components:
  - pos: -1.3260002,17.546175
    parent: 853
    type: Transform
  - canCollide: False
    type: Physics
```
5. Save file
6. Start game
7. In console, do `mapping 2 Maps/saltern.yml`

This throws an exception `Entity is not on the same map`
