### ISSUE TITLE
StackVisualizer.cs wishlist

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3699]
## Description

1. You can define what layer StackVisualizer.cs goes on. (This is so you could have the StackVisualizer and then something over it.
2. Use alphas. This entails assigning a color: to a layer in the stackLayers.
3. Show specific stacks for specific items. I don't know how this would play out YAML wise but maybe something like:
```yaml
- type: StackVisualizer
  composite: true
  stackLayers:
    - welder
      prototypes:
        - id: Welder
        - id: WelderEmergency
    - wrench
       prototypes:
         - id: Wrench
```
Something like that. This is made more confusing with tags.
4. StackVisualizers for inhands and onmobs. Stuff like belts with tools on them, stacks of food etc.
