### ISSUE TITLE
Chameleon clothing does not work properly when spawned in a loadout

### ISSUE THREAD

**Issue by beck-thompson** [space-wizards/space-station-14#37810]
## Description

Title

**Reproduction**

A spawn a loadout like this:
```
- type: entity
  parent: MobHuman
  id: MobHumanChameleonClothing
  name: syndicate medic
  components:
  - type: Loadout
    prototypes: [ FullChameleonClothing ]

- type: startingGear
  id: FullChameleonClothing
  equipment:
    head: ClothingHeadHatChameleon
    eyes: ClothingEyesChameleon
    ears: ClothingHeadsetChameleon
    mask: ClothingMaskGasChameleon
    outerClothing: ClothingOuterChameleon
    jumpsuit: ClothingUniformJumpsuitChameleon
    neck: ClothingNeckChameleon
    back: ClothingBackpackChameleon
    gloves: ClothingHandsChameleon
    shoes: ClothingShoesChameleon
    id: ChameleonPDA

```
When you chameleon your clothing it only updates the icon, not the worn texture. It also crashes when you take it off!

**Screenshots**

Stack trace after trying to unequip item
![Image](https://github.com/user-attachments/assets/f9367bf6-616c-4610-a9f9-c7b6b8a7c2df)
