### ISSUE TITLE
Conditional station availability

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5710]
## Description
Currently the only condition for a station being usable is playercount. Ideally, this would be conditions provided in the prototype, ala
```yaml
- type: gameMap
  id: snowtern
  mapName: 'Snowtern'
  mapNameTemplate: '{0} Snowtern {1}'
  nameGenerator:
    !type:NanotrasenNameGenerator
    prefixCreator: '14'
  mapPath: Maps/snowtern.yml
  conditions:
  - !type:PlayerCountCondition
    minPlayers: 0
    maxPlayers: 20
  - !type:HolidayCondition
    holiday: FestiveSeason
  overflowJobs: 
  ...
```
