### ISSUE TITLE
Lobby Music prototypes

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/space-station-14#5711]
This is mostly to allow making certain tracks require specific conditions to be met, for example a track that only plays when the server is at 40 people or more, or a track that only plays on christmas. Can tie this into the same condition system station selection uses, maybe?
```yaml
- type: lobbyMusic
  id: SpaceAsshole
  name: Space Asshole
  path: /Audio/Lobby/space_asshole.ogg
  conditions:
  - !type:PlayerCountCondition
    minPlayers: 10
    maxPlayers: 50
```
