### ISSUE TITLE
Random sprite state / color needs to be more robust

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#5852]
I have this yml:
```
- type: Sprite
    drawdepth: Mobs
    sprite: Mobs/Aliens/Guardians/guardians.rsi
    layers:
    - state: tech_basic
    - state: tech_flare
      color: "#40a7d7"
      shader: unshaded
    noRot: true
```

Ideally:
- I could set the first layer (tech_basic) to anything out of a list of options
- The 2nd layer (tech_flare) could be randomly coloured and have its state also updated to correspond with the above
- AsteroidRock is finally renamed
