### ISSUE TITLE
Solutions without ReagentId don't error

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#7297]
## Description

Somehow this still gets parsed mostly fine, but not at the same time.
```yaml
- type: SolutionContainerManager
  solutions:
    food:
      maxVol: 30
      reagents:
      - ReagentId: Nutriment
        Quantity: 20
      - Vitamin:
        Quantity: 5
```

This is from the buggy FoodCakeBase yaml. It would bug out when splitting the solution by spawning the slice, but not splitting the solution.
