### ISSUE TITLE
YAML convention

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#831]
Right now, we have no guidelines or conventions for naming things in YAML.
This makes some prototypes look inconsistent. Here's an example from `human.yml`:
```  yaml
- type: Stomach
    max_volume: 250
    digestionDelay: 20
```
As you can see, in the same component both snake_case and camelCase are used.
