### ISSUE TITLE
Prototype migration tool

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8491]
I'll take a project or whatever.

RN if I delete prototypes I have to manually update maps which is very painful. Ideally I could run the project and this would be handled by deleting them and also handling renames (either via manually supplying them or keeping track of what's diff).

**Comment by metalgearsloth** [comment]
Also this should support culling old containers because I suspect a lot of them will just hang around after getting serialized

**Comment by 0x6273** [comment]
Would something like this work?

- Store migration .yml files in new directory `Resources/MapMigrations/`.
- Migration .yml files would be a list of commands for the map migrator, can look something like this:
```yaml
- command: DeletePrototype
  id: SomePrototypeId

- command: RenamePrototype
  id: OldPrototypeId
  newId: NewPrototypeId
```
- Migration files would be named after their date, like `2022-10-02_delete_someprototype.yml`.
- Map files would store the name of the last run migration in their metadata.
- Map migrator just checks if there are files in `Resources/MapMigrations/` that are newer than in the map metadata and runs those.
