### ISSUE TITLE
Convert `AppearanceVisualizers` to components and systems

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#8995]
## Description

There are a looot of classes in content that inherit `AppearanceVisualizer` that need to be converted into a component and system. This is expounded upon in the sprite docs in wiki.js as well as this new doc I made to explain the process:

https://docs.spacestation14.io/en/engine/porting-visualizers

Should be easy to get started with. Some examples of the 'old' system:
`BuckleVisualizer`
`RollerbedVisualizer`
`KudzuVisualizer`

Some examples of the 'new' system:
`WeldableVisualizerSystem`
`GenericVisualizerSystem` (beloved)
`StickyVisualizerSystem` (also good for learning)

**Comment by Ryan089** [comment]
I would like to attempt RollerbedVisualizer.

**Comment by TekuNut** [comment]
Going to try and tackle stuff under Atmos next.

**Comment by ElectroJr** [comment]
Mirror briefly mentioned `GenericVisualizerSystem`, which is basically the system / replacement for `GenericEnumVisualizer`, but its probably worth explaining how / why to use it. Lots of appearance visualizers do really basic things like: If appearance data has this value --> set this layer's state to some value. There are lots of separate niche visualizers like this, when they really don't need to exist and can just use a generic visualizer, So taking one of the visualizers updated in #9200 as an example, it has this bit of code:
```cs
if (TryComp<SpriteComponent>(uid, out var sprite)
    && args.Component.TryGetData(DataKey, out bool enabled)
    && sprite.LayerMapTryGet(LayerMap, out var layer))
{
    sprite.LayerSetState(layer, enabled? component.EnabledState : component.DisabledState);
}
```

Instead of being a seperate visualizer, this can just use the generic visualizer, which amounts to adding the following yaml:
```yaml
- type: Appearance
- type: GenericVisualizer
   visuals:
     enum.FilterVisuals.Enabled: # <--- The appearance data key. a string or enum
       enum.GasFilterVisualLayers.Enabled: # <-- the key for the sprite layer that should be modified. Again, either a string or enum
         True:  # <-- appearance data value
           state: gasFilterOn # < --- sprite layer info corresponding to that value. Can set state, color, shader, visibility, rotation etc
         False: { state: gasFilter} # <-- IMO inlining & reducing indentation is a bit nicer to read.
```

Unless a visualizer has some complex logic or does things with animation & fancy effects, it probably doesn't need to exist and can just be generalized,

**Comment by HoofedEar** [comment]
Close pls

**Comment by mirrorcult** [comment]
this isn't done at all?

**Comment by HoofedEar** [comment]
> this isn't done at all?

I jumped the gun, I saw purple and blacked out

**Comment by ModeratelyAware** [comment]
Hi, I would like to contribute to this but noticed that TwoWayLever doesn't have a .yml file associated with it. Does one need to be made in this case?

**Comment by ElectroJr** [comment]
> TwoWayLever doesn't have a .yml file associated with it. Does one need to be made in this case?

If you mean the lever entity, every standard entity has a yml prototype. For the lever, its in switch.yml. If you mean the visualizer, components/visualizers don't have their own yaml files, they have c# and are added to entity prototypes in their yaml definitions. So either way, there shoule be no need to create a new yml file.

**Comment by ModeratelyAware** [comment]
> > TwoWayLever doesn't have a .yml file associated with it. Does one need to be made in this case?
> 
> If you mean the lever entity, every standard entity has a yml prototype. For the lever, its in switch.yml.

Ah, thanks! Turns out VS2022 was in the wrong view when I was searching, so the whole Resources folder was being excluded.. That explains it.

Quick follow-up question. For `ConveyorVisualizer` and `TwoWayLeverVisualizer` I notice that `ChangeState()` is called on initialization. Is this necessary with the transition to ECS? I noticed it worked just fine without it for Conveyor at least.

Current version:

        private void ChangeState(AppearanceComponent appearance)
        {
            //Code
        }

        public override void InitializeEntity(EntityUid entity)
        {
            base.InitializeEntity(entity);
            var entities = IoCManager.Resolve<IEntityManager>();
            var appearance = entities.EnsureComponent<ClientAppearanceComponent>(entity);
            ChangeState(appearance);
        }

        public override void OnChangeData(AppearanceComponent component)
        {
            base.OnChangeData(component);
            ChangeState(component);
        }
`

**Comment by ElectroJr** [comment]
The `AppearanceChangeEvent` will always get called at least once after an entity was initialized. As long as the appearance data is set to some value when the component that controls the visuals gets initialized, you shouldn't need to explicitly update them on init in the visualizer itself.

Just based on the code block, the update in `InitializeEntity()` was completely unnecessary.

**Comment by ModeratelyAware** [comment]
> The `AppearanceChangeEvent` will always get called at least once after an entity was initialized. As long as the appearance data is set to some value when the component that controls the visuals gets initialized, you shouldn't need to explicitly update them on init in the visualizer itself.
> 
> Just based on the code block, the update in `InitializeEntity()` was completely unnecessary.

Awesome! I thought so, thank you so much for confirming!

**Comment by ModeratelyAware** [comment]
Can #10091 have its `VisualLayers` defined in the `soil.yml`? It seems like right now everything is defined on initialization. Still pretty new, so I am not certain if this could be done better.

**Comment by ElectroJr** [comment]
It can (and should) all be defined in yaml, you just need to add the layers to the sprite component in yaml. Currently it just has
```yaml
- type: Sprite
  sprite: Structures/Hydroponics/misc.rsi
  state: soil
```
which is functionally equivalent to 
```yaml
- type: Sprite
  layers:
  - sprite: Structures/Hydroponics/misc.rsi
    state: soil
```
Basically: if no layers are explicitly defined and the  state & sprite  fields are not null, it automatically creates a single layer using those values.


You just need to add a new layer for each layer that previously got added on init. e.g:
```yaml
- type: Sprite
  layers:
  - sprite: Structures/Hydroponics/misc.rsi
    state: soil
  - sprite: Structures/Hydroponics/overlays.rsi
    state: lowhealth3
    map: [ "enum.PlantHolderLayers.HealthLight" ]
    visible: false
    shader: unshaded
```

Note that the main "sprite" field on the component is used as the default for layers. So something like
```yaml
- type: Sprite
  layers:
  - sprite: Structures/Guff/myRsi.rsi
    state: stateA
  - sprite: Structures/Guff/myRsi.rsi
    state: stateB
  - sprite: Structures/Guff/myRsi.rsi
    state: stateC
```
is equivalent to
```yaml
- type: Sprite
  sprite: Structures/Guff/myRsi.rsi
  layers:
  - state: stateA
  - state: stateB
  - state: stateC
```
which might make the yaml more compact.

But there are two more issues here. Firstly: `hydroponicsTray` inherits from `hydroponicsSoil` but defines its own sprite, which will override the inherited sprite. So you need to redefine layers for the child prototype(s).  Secondly, the soil variant is just a lump of dirt that doesn't use the indicator lights. There's no reason for it to even have the warning light layers. Really the plant holder stuff should be split into a plant holder & hydrotray visualizers.
