### ISSUE TITLE
Interacting with one specific plant in lighthouse crashes the server

### ISSUE THREAD

**Issue by EeveeTea** [space-wizards/space-station-14#9299]
There's a bioluminescent plant at the bridge in Lighthouse that is capable of crashing the server.

Reproduction:
1. Go to bridge on lighthouse
2. Approach plant on the right and click on it to root around in the roots.

![Screenshot_20220630_020046](https://user-images.githubusercontent.com/108430699/176603805-fe685987-7395-4ade-9ae9-1c486411101c.png)

**Comment by ZeroDayDaemon** [comment]
```
- uid: 12498
  type: PottedPlantBioluminscent
  components:
  - pos: -4.5,76.5
    parent: 100
    type: Transform
  - containers:
      stash: !type:ContainerSlot
        ent: null
    type: ContainerContainer
```

apparently it contains null
